# Generated by Django 4.1.7 on 2023-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_image_course_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dueDate', models.DateField()),
                ('client', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payementType', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('monthDate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='length',
        ),
        migrations.RemoveField(
            model_name='course',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
    ]
