# Generated by Django 4.1.7 on 2023-03-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_freelance_orders_premium_user_remove_course_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
