# Generated by Django 4.1.7 on 2023-04-01 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('tele', models.CharField(default=None, max_length=15)),
                ('completeBy', models.DateField()),
                ('title', models.CharField(default=None, max_length=150)),
                ('details', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TutorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('tele', models.CharField(default=None, max_length=15)),
                ('sessionsPW', models.IntegerField()),
                ('course', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
