# Generated by Django 4.1.7 on 2023-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_hire_tutorbooking_tutoring_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='dueDate',
            field=models.CharField(max_length=15),
        ),
    ]
