# Generated by Django 4.1.6 on 2023-04-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_alter_tutorbooking_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='applications',
            field=models.CharField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='tele',
            field=models.CharField(default='', max_length=100),
        ),
    ]
