# Generated by Django 4.1.6 on 2023-04-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_freelance_applications_profile_tele'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('_id', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='freelance',
            name='applications',
            field=models.CharField(default='', max_length=200),
        ),
    ]
