# Generated by Django 4.1.6 on 2023-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_clicks_alter_freelance_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicks',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
