# Generated by Django 4.1.7 on 2023-05-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_clicks__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tele',
        ),
    ]
