# Generated by Django 4.1.7 on 2023-05-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_profile_premium_remove_profile_tele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='monthDate',
        ),
    ]
