# Generated by Django 4.1.7 on 2023-05-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_premium_id_alter_premium_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
